[package]
name = "postly_client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "=1.8.1"
solana-client = "=1.8.1"
borsh = "0.9.1"
borsh-derive = "0.9.1"
util = { path = "../util" }
shellexpand = "2.1.0"